# Jumpsuit
- type: loadout
  id: JumpsuitHoSBlue
  equipment: 
    jumpsuit: ClothingUniformJumpsuitHoSBlue

# Hats
- type: loadout
  id: HoSWidebrimHarmony
  equipment:
    hat: ClothingHeadHatHoSWidebrimHarmony