- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeEnergyCarbineHarmony
  name: energy carbine safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyCarbineFilledHarmony
      amount: 2
    - id: EnergyCartridgeHarmony
      amount: 2
